title = "配置新增"
route = "/api/config/add"

[request]
name       = ["string", "名称",    "order=1"]
k          = ["string", "键",      "order=2"]
v          = ["string", "值",      "order=4"]
data_type  = ["string", "数据类型", "order=4"]

[response]
id  = ["int", "新增ID"]