title = "配置新增"
route = "/api/config/add"

[request]
name       = ["string", "名称"]
k          = ["string", "键"]
v          = ["string", "值"]
data_type  = ["string", "数据类型"]

[response]
id  = ["int", "新增ID"]