title = "配置列表"
route = "/api/config/list"

[request]
page      = ["int", "页码", "order=1"]
page_size = ["int", "每页数量", "order=2"]
key       = ["string", "搜索关键词", "order=3"]

[response]
datas   = ["array[item]", "数据", "order=1"]
count   = ["int", "总数", "order=2"]
types   = ["array[type]", "类型标识", "order=3"]

[component.item]
id         = ["int", "配置ID", "order=1"]
name       = ["string", "名称", "order=2"]
k          = ["string", "键", "order=3"]
v          = ["string", "值", "order=4"]
data_type  = ["string", "数据类型", "order=5"]
created_at = ["string", "创建时间", "order=6"]

[component.type]
k          = ["string", "键", "order=1"]
v          = ["string", "值", "order=2"]