title = "配置更新"
route = "/api/config/update"

[request]
id         = ["int", "配置ID",  "order=1"]
name       = ["string", "名称", "order=2"]
k          = ["string", "键",   "order=3"]
v          = ["string", "值",   "order=4"]
data_type  = ["string", "数据类型", "order=5"]

[response]
